#!/bin/sh
cd "${0%/*}" || exit 1
. "${WM_PROJECT_DIR:?}/bin/tools/RunFunctions"

restore0Dir

runApplication blockMesh
runApplication checkMesh -constant

NP=$(getNumberOfProcessors)

if [ "$NP" -gt 1 ]; then
    runApplication decomposePar
    runParallel $(getApplication)
    runApplication reconstructPar
else
    runApplication $(getApplication)
fi

echo "Done. FW-H observer signals in postProcessing/fwhWall/acousticData/"
