r"""Acoustic source localization on a permeable FW-H surface (the sigma method).

This module turns fwhFoam's permeable-surface Cauchy data -- the surface
pressure ``p`` and normal velocity ``v_n = u.n`` sampled over time -- into a
frequency-domain **surface sound-power density** ``sigma`` that answers a
question the far-field FW-H pressure cannot: *where on the surface does the
radiated sound actually come from?*

Theory (Delfs & Ruck, JSV 586 (2024) 118490; Sharma, spectral theory of the
diffraction filter and the exact surface power density). The radiating field
generated by Cauchy data ``(phi, psi)`` on a closed surface ``S``, with

    phi = p_hat(xi; omega)              (complex surface pressure)
    psi = dp/dn = -i*omega*rho*vn_hat   (complex normal-derivative datum)

has the far-field directivity amplitude

    F(xhat) = (1/4pi) * closed_int [ i k (xhat.n) phi - psi ] e^{i k xhat.xi} dS

and radiated power ``P = (1/(2 rho c)) * closed_int |F|^2 dOmega``. Doing the
angular integrals in closed form gives an exact **two-point** surface density
whose integral equals that power,

    sigma(xi) = (1/(32 pi^2 rho c)) Re closed_int {
            k^2 (n.W(d).n') phi phi'^*
          - i k (n.V(d))    phi psi'^*
          + i k (n'.V(d))   psi phi'^*
          + J0(d)           psi psi'^*  } dS(xi')

with d = xi - xi', z = k|d|, dh = d/|d|, and the closed-form angular kernels

    W_ij(d) = 4pi [ delta_ij j1(z)/z - dh_i dh_j j2(z) ]   (W_ij(0) = 4pi/3 delta_ij)
    V_i(d)  = 4pi i j1(z) dh_i                              (V(0) = 0)
    J0(d)   = 4pi j0(z)

so that ``closed_int sigma dS = P``. On a rigid/impermeable surface ``psi = 0``
and only the first (pressure-pressure) block survives -- the classical
rigid-wall density. ``sigma`` is signed: it can be locally negative, because
radiated power is a pairwise (two-point) quantity, not a pointwise one.

The identity ``closed_int sigma dS == P_farfield`` is a built-in verification:
the same data produce the localization map and, independently, the far-field
power, and they must agree.

References
----------
J. W. Delfs, B. Ruck, A quantity to identify turbulence related sound
generation on surfaces, J. Sound Vib. 586 (2024) 118490.
"""

from __future__ import annotations

import numpy as np
from scipy.special import spherical_jn


# --------------------------------------------------------------------------
# Frequency-domain Cauchy data from time histories
# --------------------------------------------------------------------------

def cauchy_spectrum(data, window="hann", detrend=True):
    r"""FFT the permeable-surface time histories into complex Cauchy data.

    Parameters
    ----------
    data : pyfwh.io.FWHData
        Permeable-surface data: ``.p`` (T,N) gauge pressure [Pa], ``.u``
        (T,N,3) fluid velocity [m/s], ``.normals`` (N,3), ``.times`` (T,).
    window : {"hann", None}
        Time window applied before the FFT.
    detrend : bool
        Remove the per-face temporal mean before windowing.

    Returns
    -------
    freqs : (F,) one-sided frequencies [Hz]
    phat  : (F,N) complex surface pressure spectra [Pa]
    vnhat : (F,N) complex normal-velocity spectra [m/s]
    scale : float
        Amplitude scale already applied (single-sided, window-corrected), so
        that ``phat`` is the physical complex amplitude of each spectral line.
    """
    t = np.asarray(data.times, float)
    dt = float(np.mean(np.diff(t)))
    n = t.size

    p = np.asarray(data.p, float)                    # (T,N)
    vn = np.einsum("tni,ni->tn", np.asarray(data.u, float),
                   np.asarray(data.normals, float))  # (T,N)

    if detrend:
        p = p - p.mean(axis=0, keepdims=True)
        vn = vn - vn.mean(axis=0, keepdims=True)

    if window == "hann":
        w = np.hanning(n)
    elif window in (None, "none", "boxcar"):
        w = np.ones(n)
    else:
        raise ValueError(f"unknown window {window!r}")

    cg = w.sum() / n                                 # coherent gain
    P = np.fft.rfft(p * w[:, None], axis=0)
    V = np.fft.rfft(vn * w[:, None], axis=0)
    freqs = np.fft.rfftfreq(n, dt)

    # single-sided physical amplitude of each line
    sc = 2.0 / (n * cg)
    phat = sc * P
    vnhat = sc * V
    phat[0] *= 0.5
    vnhat[0] *= 0.5
    if n % 2 == 0:
        phat[-1] *= 0.5
        vnhat[-1] *= 0.5
    return freqs, phat, vnhat, sc


# --------------------------------------------------------------------------
# Closed-form angular kernels
# --------------------------------------------------------------------------

def _kernels(P, Q, k):
    """Angular-integral kernels W_ij, V_i, J0 for all node pairs P x Q."""
    d = P[:, None, :] - Q[None, :, :]              # (A,B,3)
    dn = np.linalg.norm(d, axis=-1)                # (A,B)
    z = k * dn
    with np.errstate(divide="ignore", invalid="ignore"):
        dh = np.where(dn[..., None] > 0, d / dn[..., None], 0.0)
        j1z = np.where(z > 0, spherical_jn(1, z) / np.where(z > 0, z, 1.0),
                       1.0 / 3.0)
    j0 = spherical_jn(0, z)
    j1 = spherical_jn(1, z)
    j2 = spherical_jn(2, z)
    eye = np.eye(3)
    Wij = 4 * np.pi * (j1z[..., None, None] * eye
                       - j2[..., None, None] * dh[..., :, None] * dh[..., None, :])
    Vi = 4 * np.pi * 1j * j1[..., None] * dh
    J0 = 4 * np.pi * j0
    return Wij, Vi, J0


# --------------------------------------------------------------------------
# Surface power density (the localization map)
# --------------------------------------------------------------------------

def sigma_density(pts, n, area, phat, vnhat, omega, rho, c, chunk=None):
    r"""Two-point surface sound-power density sigma at one frequency.

    Parameters
    ----------
    pts   : (N,3) face centres
    n     : (N,3) outward unit normals
    area  : (N,) face areas (quadrature weights)
    phat  : (N,) complex surface pressure at this frequency [Pa]
    vnhat : (N,) complex normal velocity at this frequency [m/s]
    omega : angular frequency [rad/s]
    rho, c: ambient density and sound speed
    chunk : optional row block size to bound memory (O(N*chunk) instead of N^2)

    Returns
    -------
    sigma : (N,) real surface power density [W/m^2], with sum(area*sigma) = P
    P     : float, total radiated power [W]
    """
    pts = np.asarray(pts, float)
    n = np.asarray(n, float)
    area = np.asarray(area, float)
    phi = np.asarray(phat, complex)
    psi = -1j * omega * rho * np.asarray(vnhat, complex)   # dp/dn datum
    k = omega / c
    N = pts.shape[0]
    pref = 1.0 / (32 * np.pi**2 * rho * c)

    sigma = np.zeros(N)
    if chunk is None:
        chunk = N

    for a0 in range(0, N, chunk):
        a1 = min(a0 + chunk, N)
        Wij, Vi, J0 = _kernels(pts[a0:a1], pts, k)          # (a,N,..)
        nWn = np.einsum("ai,abij,bj->ab", n[a0:a1], Wij, n)
        nVa = np.einsum("ai,abi->ab", n[a0:a1], Vi)         # n_a . V
        nVb = np.einsum("bi,abi->ab", n, Vi)                # n_b . V
        pp = phi[a0:a1, None] * np.conj(phi)[None, :]
        ps = phi[a0:a1, None] * np.conj(psi)[None, :]
        sp = psi[a0:a1, None] * np.conj(phi)[None, :]
        ss = psi[a0:a1, None] * np.conj(psi)[None, :]
        integrand = (k**2 * nWn * pp - 1j * k * nVa * ps
                     + 1j * k * nVb * sp + J0 * ss)         # (a,N)
        # density at face a: sum_b area_b * integrand  (times prefactor)
        sigma[a0:a1] = pref * np.real(integrand @ area)

    P = float(np.sum(area * sigma))
    return sigma, P


# --------------------------------------------------------------------------
# Independent cross-checks
# --------------------------------------------------------------------------

def farfield_power(pts, n, area, phat, vnhat, omega, rho, c, ndir=(40, 80)):
    r"""Radiated power via the far-field amplitude F (independent of sigma).

    Returns (P, xhat, F) with P = sum_Omega |F|^2 / (2 rho c).
    """
    pts = np.asarray(pts, float)
    n = np.asarray(n, float)
    area = np.asarray(area, float)
    phi = np.asarray(phat, complex)
    psi = -1j * omega * rho * np.asarray(vnhat, complex)
    k = omega / c

    xhat, wo = _sphere_dirs(*ndir)
    e = np.exp(1j * k * xhat @ pts.T)                       # (D,N)
    xn = xhat @ n.T                                          # (D,N)
    F = (1 / (4 * np.pi)) * np.sum(
        area[None, :] * (1j * k * xn * phi[None, :] - psi[None, :]) * e, axis=1)
    P = float(np.sum(wo * np.abs(F)**2) / (2 * rho * c))
    return P, xhat, F


def pointwise_power(n, area, phat, vnhat):
    r"""Power through the surface as the real acoustic intensity.

    P = closed_int (1/2) Re(p_hat * conj(vn_hat)) dS. For the *exact* acoustic
    Cauchy data this equals the radiated power and provides a third, fully
    independent check of the sigma identity.
    """
    area = np.asarray(area, float)
    return float(0.5 * np.sum(area * np.real(np.asarray(phat, complex)
                                             * np.conj(np.asarray(vnhat, complex)))))


def _sphere_dirs(nth, nph):
    """Gauss-Legendre(theta) x uniform(phi) unit directions and weights."""
    mu, wmu = np.polynomial.legendre.leggauss(nth)
    th = np.arccos(mu)
    ph = np.linspace(0, 2 * np.pi, nph, endpoint=False)
    TH, PH = np.meshgrid(th, ph, indexing="ij")
    w = np.outer(wmu, np.full(nph, 2 * np.pi / nph)).ravel()
    x = np.stack([np.sin(TH) * np.cos(PH),
                  np.sin(TH) * np.sin(PH),
                  np.cos(TH)], -1).reshape(-1, 3)
    return x, w


# --------------------------------------------------------------------------
# Band integration
# --------------------------------------------------------------------------

def sigma_band(pts, n, area, freqs, phat, vnhat, rho, c, fmin, fmax,
               chunk=None):
    r"""Band-integrated sigma map and power over [fmin, fmax].

    Sums the single-frequency densities over the spectral lines in the band.
    Returns (sigma_band (N,), P_band, lines) where lines is the list of
    (freq, P_sigma, P_farfield, P_pointwise) per line for the identity check.
    """
    sel = np.where((freqs >= fmin) & (freqs <= fmax) & (freqs > 0))[0]
    N = pts.shape[0]
    sig = np.zeros(N)
    lines = []
    for i in sel:
        om = 2 * np.pi * freqs[i]
        s, Ps = sigma_density(pts, n, area, phat[i], vnhat[i], om, rho, c,
                              chunk=chunk)
        Pf, _, _ = farfield_power(pts, n, area, phat[i], vnhat[i], om, rho, c)
        Pp = pointwise_power(n, area, phat[i], vnhat[i])
        sig += s
        lines.append((float(freqs[i]), Ps, Pf, Pp))
    return sig, float(np.sum(area * sig)), lines
